### ISSUE TITLE
Create AuxImage error 

### ISSUE THREAD

**Issue by astylianGR** [oracle/weblogic-toolkit-ui#145]
When using the UI and trying to create an Aux image we are getting the following error: 

JDK version is 11.0.15.1+2-LTS-10
JAVA_HOME = /usr/java/jdk-11.0.15.1
CLASSPATH = /opt/WebLogic Kubernetes Toolkit UI/tools/weblogic-deploy/lib/weblogic-deploy-core.jar:/u01/Middleware/wlserver/server/lib/weblogic.jar
JAVA_PROPERTIES = -Djava.util.logging.config.class=oracle.weblogic.deploy.logging.WLSDeployLoggingConfig -Dpython.cachedir.skip=true -Dpython.console= 
/usr/java/jdk-11.0.15.1/bin/java -cp /opt/WebLogic Kubernetes Toolkit UI/tools/weblogic-deploy/lib/weblogic-deploy-core.jar:/u01/Middleware/wlserver/server/lib/weblogic.jar           -Djava.util.logging.config.class=oracle.weblogic.deploy.logging.WLSDeployLoggingConfig -Dpython.cachedir.skip=true -Dpython.console=            -Dpython.path=/u01/Middleware/wlserver/common/wlst/modules/jython-modules.jar/Lib           org.python.util.jython           /opt/WebLogic Kubernetes Toolkit UI/tools/weblogic-deploy/lib/python/prepare_model.py -oracle_home /u01/Middleware -model_file /home/opc/edea-oke-prod-models/model.yaml -output_dir /home/opc/prepareModelPrNofw -target wko
####<Jun 28, 2022 3:40:33 PM> <INFO> <WLSDeployLoggingConfig> <<init>> <> <The prepareModel program will write its log to /opt/WebLogic Kubernetes Toolkit UI/tools/weblogic-deploy/logs/prepareModel.log>
####<Jun 28, 2022 3:40:35 PM> <INFO> <WebLogicDeployToolingVersion> <logVersionInfo> <WLSDPLY-01750> <The WebLogic Deploy Tooling prepareModel version is 2.1.0:.a158563:Feb 18, 2022 19:09 UTC>
####<Jun 28, 2022 3:40:35 PM> <INFO> <XPathUtil> <getPSU> <> <No patches home at inventory/patches>
####<Jun 28, 2022 3:40:35 PM> <INFO> <path_utils> <find_config_path> <WLSDPLY-01725> <Using configuration file /opt/WebLogic Kubernetes Toolkit UI/tools/wdt-config/targets/wko/target.json>
####<Jun 28, 2022 3:40:35 PM> <INFO> <XPathUtil> <getPSU> <> <No patches home at /u01/Middleware/inventory/patches>
####<Jun 28, 2022 3:40:35 PM> <INFO> <path_utils> <find_config_path> <WLSDPLY-01725> <Using configuration file /opt/WebLogic Kubernetes Toolkit UI/tools/wdt-config/targets/wko/target.json>
####<Jun 28, 2022 3:40:36 PM> <INFO> <path_utils> <find_config_path> <WLSDPLY-01725> <Using configuration file /opt/WebLogic Kubernetes Toolkit UI/tools/wdt-config/targets/wko/target.json>
####<Jun 28, 2022 3:40:36 PM> <INFO> <filter_helper> <_apply_filter> <WLSDPLY-20034> <Applying filter with ID "wko_filter">
####<Jun 28, 2022 3:40:36 PM> <INFO> <wlsdeploy.prepare_model> <_apply_filter_and_inject_variable> <WLSDPLY-06014> <Filters applied to the model>
####<Jun 28, 2022 3:40:36 PM> <INFO> <path_utils> <find_config_path> <WLSDPLY-01725> <Using configuration file /opt/WebLogic Kubernetes Toolkit UI/tools/wdt-config/targets/wko/target.json>
####<Jun 28, 2022 3:40:36 PM> <INFO> <variable_injector> <inject_variables_keyword_file> <WLSDPLY-19533> <Will inject variable replacement strings into model using keyword directions found in file /opt/WebLogic Kubernetes Toolkit UI/tools/wdt-config/targets/wko/target.json>
####<Jun 28, 2022 3:40:37 PM> <INFO> <variable_injector> <inject_variables_keyword_file> <WLSDPLY-19519> <No variables were inserted into the model during variable replacement>
####<Jun 28, 2022 3:40:37 PM> <INFO> <path_utils> <find_config_path> <WLSDPLY-01725> <Using configuration file /opt/WebLogic Kubernetes Toolkit UI/tools/wdt-config/targets/wko/target.json>
####<Jun 28, 2022 3:40:37 PM> <INFO> <filter_helper> <_apply_filter> <WLSDPLY-20034> <Applying filter with ID "wko_filter">
####<Jun 28, 2022 3:40:38 PM> <INFO> <variables> <_substitute> <WLSDPLY-01739> <Could not resolve secret token "__weblogic-credentials__:username". Known secrets include: .  Secrets can only be resolved in Kubernetes environment. The secret tokens name and keys must have a matching Kubernetes secret name and literals in the same namespace. For WebLogic Kubernetes Operator deployment, you must specify the secret name in "domain.spec.configuration.secrets">
####<Jun 28, 2022 3:40:38 PM> <INFO> <variables> <_substitute> <WLSDPLY-01739> <Could not resolve secret token "__weblogic-credentials__:password". Known secrets include: .  Secrets can only be resolved in Kubernetes environment. The secret tokens name and keys must have a matching Kubernetes secret name and literals in the same namespace. For WebLogic Kubernetes Operator deployment, you must specify the secret name in "domain.spec.configuration.secrets">
####<Jun 28, 2022 3:40:38 PM> <INFO> <path_utils> <find_config_path> <WLSDPLY-01725> <Using configuration file /opt/WebLogic Kubernetes Toolkit UI/tools/wdt-config/targets/wko/target.json>
####<Jun 28, 2022 3:40:38 PM> <INFO> <filter_helper> <_apply_filter> <WLSDPLY-20034> <Applying filter with ID "wko_filter">
####<Jun 28, 2022 3:40:38 PM> <INFO> <vz_config_helper> <_create_file> <WLSDPLY-01662> <Creating target configuration file /home/opc/prepareModelPrNofw/wko-domain.yaml>

Issue Log for prepareModel version 2.1.0 running WebLogic version 14.1.1.0.0 offline mode:

Total:       WARNING :     0    SEVERE :     0

prepareModel.sh completed successfully (exit code = 0)
/opt/WebLogic Kubernetes Toolkit UI/tools/weblogic-deploy/bin/prepareModel.sh exited with exit code 0
[INFO   ] WebLogic Image Tool version 1.11.0
[INFO   ] Image Tool build ID: c85d3beb-322f-4a37-8e07-f2b5ea3b1791
[INFO   ] Temporary directory used for image build context: /tmp/wlsimgbuilder_temp2770645632245691960
[INFO   ] Copying /home/opc/edea-oke-prod-models/model.yaml to build context folder.
[INFO   ] Copying /home/opc/Downloads/weblogic-deploy.tar.gz to build context folder.
[INFO   ] Starting build: /usr/bin/podman build --no-cache --force-rm --tag lhr.ocir.io/lrtg4a4iixwu/cfl-prod-reg-aux-image:4 /tmp/wlsimgbuilder_temp2770645632245691960
java.io.IOException: Build command failed with error: Error: kernel does not support overlay fs: unable to create kernel-style whiteout: operation not permitted

	at com.oracle.weblogic.imagetool.util.Utils.processError(Utils.java:272)
	at com.oracle.weblogic.imagetool.util.Utils.runDockerCommand(Utils.java:250)
	at com.oracle.weblogic.imagetool.util.Utils.removeIntermediateDockerImages(Utils.java:706)
	at com.oracle.weblogic.imagetool.cli.menu.CommonOptions.cleanup(CommonOptions.java:240)
	at com.oracle.weblogic.imagetool.cli.menu.CreateAuxImage.call(CreateAuxImage.java:55)
	at com.oracle.weblogic.imagetool.cli.menu.CreateAuxImage.call(CreateAuxImage.java:21)
	at picocli.CommandLine.executeUserObject(CommandLine.java:1953)
	at picocli.CommandLine.access$1300(CommandLine.java:145)
	at picocli.CommandLine$RunLast.executeUserObjectOfLastSubcommandWithSameParent(CommandLine.java:2352)
	at picocli.CommandLine$RunLast.handle(CommandLine.java:2346)
	at picocli.CommandLine$RunLast.handle(CommandLine.java:2311)
	at picocli.CommandLine$AbstractParseResultHandler.execute(CommandLine.java:2179)
	at picocli.CommandLine.execute(CommandLine.java:2078)
	at com.oracle.weblogic.imagetool.cli.ImageTool.run(ImageTool.java:79)
	at com.oracle.weblogic.imagetool.cli.ImageTool.main(ImageTool.java:51)
/opt/WebLogic Kubernetes Toolkit UI/tools/imagetool/bin/imagetool.sh exited with exit code 0

**Comment by mriccell** [comment]
This error only happens when creating an AUX image with Podman and OL 8
If the WKT UI is run with root access there is no error.

**Comment by jshum2479** [comment]
Hmm,  I have similar environment.   I don't have docker installed in my environment.

cat /etc/os-release 
NAME="Oracle Linux Server"
VERSION="8.6"
ID="ol"
ID_LIKE="fedora"
VARIANT="Server"
VARIANT_ID="server"
VERSION_ID="8.6"
PLATFORM_ID="platform:el8"
PRETTY_NAME="Oracle Linux Server 8.6"
ANSI_COLOR="0;31"
CPE_NAME="cpe:/o:oracle:linux:8:6:server"
HOME_URL="https://linux.oracle.com/"
BUG_REPORT_URL="https://bugzilla.oracle.com/"

ORACLE_BUGZILLA_PRODUCT="Oracle Linux 8"
ORACLE_BUGZILLA_PRODUCT_VERSION=8.6
ORACLE_SUPPORT_PRODUCT="Oracle Linux"
ORACLE_SUPPORT_PRODUCT_VERSION=8.6

[root@johnny-oel8 ~]# rpm -qa | grep -i podman
podman-catatonit-4.0.2-6.module+el8.6.0+20665+a3b29bef.x86_64
podman-4.0.2-6.module+el8.6.0+20665+a3b29bef.x86_64


and it's working both opc or oracle (I added) user.


Did you install docker ?

**Comment by astylianGR** [comment]
I have removed the podman-docker-2:4.0.2-6.module+el8.6.0+20665+a3b29bef.noarch and opened UI as opc and the issue is still reproducible

**Comment by astylianGR** [comment]
logs for the UI with logger to finer

**Comment by jshum2479** [comment]
How do you launch the UI ?  From the desktop or through a terminal?   I use the desktop, search for UI and then launch it.   Can you modify the the  imagetool.sh  and echo the PATH to see what it is?

Mine is like this

PATH IS  /home/opc/.local/bin:/home/opc/bin:/usr/local/bin:/usr/bin:/usr/local/sbin:/usr/sbinundefined

**Comment by astylianGR** [comment]
I also use the Desktop and this is the path

 /home/opc/.local/bin:/home/opc/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/binundefined

**Comment by jshum2479** [comment]
We found the problem, it should be fix in next release which may happen today.

**Comment by astylianGR** [comment]
great please let me know when the release will be ready for download and I will also notify the customer. 

Thanks!

**Comment by robertpatrick** [comment]
#147 should resolve your problem.  We will get the 1.2.0 release cut ASAP and then you can try it out...

**Comment by robertpatrick** [comment]
@astylianGR 1.2.0 has been released.  Please try it out and let us know if this resolved the problem.

**Comment by robertpatrick** [comment]
Closing due to lack of user feedback on the delivered fix.
