### ISSUE TITLE
Error WLSDPLY-20035 in Prepare model

### ISSUE THREAD

**Issue by AndressaSiqueira** [oracle/weblogic-toolkit-ui#203]
[logtool.txt](https://github.com/oracle/weblogic-toolkit-ui/files/10572251/logtool.txt)

**Comment by robertpatrick** [comment]
@AndressaSiqueira I am not sure what you expect us to do with this file.  The error is in WDT's `prepareModel` script execution so you need to find the prepareModel.log file that corresponds to the WKTUI action.  WDT uses the following logic to place the log file (based on write access to the directory):

- $WLSDEPLOY_HOME/logs/prepareModel.log
- `pwd`/logs/prepareModel.log
- /tmp/wdt-logs<random characters>/prepareModel.log

Please provide the complete prepareModel.log file showing the actual details of the WDT error.
